name: Build Release
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: package
      run: |
        zip /tmp/mtathena.mtlib ./*
    - name: Upload Package
      id: upload-package
      uses: actions/upload-release-asset@v1
      
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: /tmp/mtathena.mtlib
        asset_name: Tokens-${{ github.event.release.tag_name }}.mtlib
        asset_content_type: application/octet-stream
